apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: star-pipetogrep-org
  namespace: default
spec:
  secretName: star-pipetogrep-org-tls
  issuerRef:
    name: letsencrypt-cluster
    kind: ClusterIssuer
  commonName: '*.pipetogrep.org'
  dnsNames:
    - pipetogrep.org
  acme:
    config:
      - dns01:
          provider: route53
        domains:
          - '*.pipetogrep.org'
          - 'pipetogrep.org'
